spring.application.name=JobSearchProject

spring.datasource.url=jdbc:postgresql://localhost:5432/jobsearch
spring.datasource.username=jobsearch
spring.datasource.password=jobsearch


#for docker
# use this postgres credentials
#spring.datasource.url=${SPRING_DATASOURCE_URL}
#spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
# spring.datasource.driver-class-name=org.postgresql.Driver  # Optional, Spring Boot can auto-detect it

# Hibernate settings
spring.jpa.hibernate.ddl-auto=update   
spring.jpa.show-sql=true              
spring.main.allow-bean-definition-overriding=true

#ensures that the data.sql file is executed every time the application starts,
#regardless of whether the schema already exists.
spring.sql.init.mode=always

# Server Configuration
server.port=8080