spring.application.name=JobSearchProject

spring.datasource.url=jdbc:postgresql://localhost:5432/jobsearch
spring.datasource.username=jobsearch
spring.datasource.password=jobsearch


#for docker
# use this postgres credentials
#spring.datasource.url=${SPRING_DATASOURCE_URL}
#spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
# spring.datasource.driver-class-name=org.postgresql.Driver  # Optional, Spring Boot can auto-detect it

# Hibernate settings
spring.jpa.hibernate.ddl-auto=update   
spring.jpa.show-sql=true              
spring.main.allow-bean-definition-overriding=true

#Setting it to on-schema-create will run the script only
# when the schema is created (useful if you only want it on the initial setup).
 spring.sql.init.mode=always
 
 
 logging.level.root=INFO


# Server Configuration
server.port=8080