spring.application.name=JobSearchProject

spring.datasource.url=jdbc:postgresql://localhost:5432/jobsearch
spring.datasource.username=jobsearch
spring.datasource.password=jobsearch

# Hibernate settings
spring.jpa.hibernate.ddl-auto=update   
spring.jpa.show-sql=true              
spring.main.allow-bean-definition-overriding=true