INSERT INTO job_category (category_name) VALUES ('IT') ON CONFLICT DO NOTHING;
INSERT INTO job_category (category_name) VALUES ('Marketing') ON CONFLICT DO NOTHING;
INSERT INTO job_category (category_name) VALUES ('Sales') ON CONFLICT DO NOTHING;
INSERT INTO job_category (category_name) VALUES ('Finance') ON CONFLICT DO NOTHING;
INSERT INTO job_category (category_name) VALUES ('Healthcare') ON CONFLICT DO NOTHING;
INSERT INTO job_category (category_name) VALUES ('Engineering') ON CONFLICT DO NOTHING;
INSERT INTO job_category (category_name) VALUES ('Education') ON CONFLICT DO NOTHING;
INSERT INTO job_category (category_name) VALUES ('Customer Service') ON CONFLICT DO NOTHING;
INSERT INTO job_category (category_name) VALUES ('Human Resources') ON CONFLICT DO NOTHING;
INSERT INTO job_category (category_name) VALUES ('Legal') ON CONFLICT DO NOTHING;