version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8081:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/jobsearch
      SPRING_DATASOURCE_USERNAME: jobsearch
      SPRING_DATASOURCE_PASSWORD: jobsearch
    networks:
      - jobsearch-network

  db:
    image: postgres:16.4
    environment:
      POSTGRES_DB: jobsearch
      POSTGRES_USER: jobsearch
      POSTGRES_PASSWORD: jobsearch
    ports:
      - "5435:5432"
    networks:
      - jobsearch-network

networks:
  jobsearch-network:
    driver: bridge
